// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoptmdFQVcVo_NoselXBeF-MH13kpDasw',
    appId: '1:852258747070:web:cdd7f8e46f040b46ed64ef',
    messagingSenderId: '852258747070',
    projectId: 'daln-prj',
    authDomain: 'daln-prj.firebaseapp.com',
    storageBucket: 'daln-prj.appspot.com',
    measurementId: 'G-N81DN60VP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjJiHFGSwwFjSLUHd3fA0P5ne6aF0x7wQ',
    appId: '1:852258747070:android:3cbcb631f724be99ed64ef',
    messagingSenderId: '852258747070',
    projectId: 'daln-prj',
    storageBucket: 'daln-prj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRsH__MTEN6hjdiqFxWi3CflM3AVDpcZk',
    appId: '1:852258747070:ios:5ccd1948899887d6ed64ef',
    messagingSenderId: '852258747070',
    projectId: 'daln-prj',
    storageBucket: 'daln-prj.appspot.com',
    iosBundleId: 'com.example.daln',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRsH__MTEN6hjdiqFxWi3CflM3AVDpcZk',
    appId: '1:852258747070:ios:8faf4cf8b6674fb2ed64ef',
    messagingSenderId: '852258747070',
    projectId: 'daln-prj',
    storageBucket: 'daln-prj.appspot.com',
    iosBundleId: 'com.example.daln.RunnerTests',
  );
}
